language: python
python:
  - "3.6.8"

services:
  - couchdb

# command to install dependencies
install: "pip install -r requirements.txt"

before_script:
  - curl -X PUT localhost:5984/test

script:
  - nosetests

after_success:
  - codecov